---
name: zuban
description: Zuban is a high-performance LSP and type checker implemented in Rust, by the author of Jedi.
homepage: https://zubanls.com/
licenses:
  - AGPL-3.0
languages:
  - Python
categories:
  - Linter
  - LSP

source:
  id: pkg:pypi/zuban@0.0.24

bin:
  zuban: pypi:zuban

